### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'pretrain_saver'

### ISSUE THREAD

**Issue by kinsumliu** [shaohua0116/DCGAN-Tensorflow#2]
In your `trainer.py`, `self.pretrain_saver` does not exist. If people want to resume training job from checkpoint like `python trainer.py --dataset MNIST --checkpoint default-MNIST_lr_0.0001_update_G5_D1-XXXX-XXX`, it will fail.

Suggestion: maybe just use the supervisor to restore the checkpoint?

**Comment by shaohua0116** [comment]
Thanks for raising the issue. I fixed it (trainer.py line 130).
